version: '3'

networks:
  services:
    driver: bridge

services:
  db: 
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - services
    ports:
      - "5432:5432"

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    ports:
      - '3000:3000'
    networks:
      - services
    environment:
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_ENV=${NODE_ENV}

  questionario:
    build: ./questionario
    container_name: questionario
    command: ash docker-entrypoint.sh
    volumes:
      - ./questionario:/questionario
    environment:
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
    ports:
      - "8001:8001"
    networks:
      - services
    depends_on:
      - db
      - frontend

  frases:
    build: ./frases
    container_name: frases
    command: ash docker-entrypoint.sh
    volumes:
      - ./frases:/frases
    ports:
      - "8002:8002"
    networks:
      - services
    environment:
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}

    depends_on:
      - db
      - frontend

  depoimentos:
    build: ./depoimentos
    container_name: depoimentos
    command: ash docker-entrypoint.sh
    volumes:
      - ./depoimentos:/depoimentos
    ports:
      - "8003:8003"
    networks:
      - services
    environment:
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
    depends_on:
      - db
      - frontend

  autenticador:
    build: ./autenticador
    container_name: autenticador
    command: ash docker-entrypoint.sh
    volumes:
      - ./autenticador:/autenticador
    ports:
      - "8004:8004"
    networks:
      - services
    environment:
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
    depends_on:
      - db
      - frontend
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx_violeta
    ports:
      - "80:80"
      #- "443:443"
    restart: unless-stopped
    networks:
      - services
    environment:
      NAME_SPACE: ${NAME_SPACE}
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      # - /etc/letsencrypt:/etc/letsencrypt
    links:
      - "questionario"
      - "frontend"
      - "frases"
      - "depoimentos"
      - "autenticador"
