# Generated by Django 2.1.7 on 2021-03-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id_depoimento', models.AutoField(primary_key=True, serialize=False)),
                ('aprovado', models.BooleanField(default=False)),
                ('ds_depoimento', models.TextField()),
            ],
        ),
    ]
