# Generated by Django 2.1.7 on 2021-03-30 21:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadProfissionais',
            fields=[
                ('nome_profissional', models.CharField(max_length=30)),
                ('ds_profissional', models.TextField()),
                ('id_profissional', models.AutoField(primary_key=True,
                 serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaViolencia',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True,
                                                  serialize=False)),
                ('nome_categoria', models.CharField(max_length=200)),
                ('ds_categoria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContatoQuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContatoViolencia',
            fields=[
                ('id_contato', models.AutoField(primary_key=True,
                                                serialize=False)),
                ('nome_contato', models.CharField(max_length=200)),
                ('numero_contato', models.CharField(max_length=50)),
                ('ds_contato', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id_questionario', models.AutoField(primary_key=True,
                                                     serialize=False)),
                ('arvore_decisao',
                 django.contrib.postgres.fields.jsonb.JSONField()),
                ('categoria_violencia',
                 models.ForeignKey
                 (on_delete=django.db.models.deletion.CASCADE,
                  to='questionario.CategoriaViolencia')),
            ],
        ),
        migrations.AddField(
            model_name='contatoquestionario',
            name='contato_fk',
            field=models.ForeignKey
            (on_delete=django.db.models.deletion.CASCADE,
             to='questionario.ContatoViolencia'),
        ),
        migrations.AddField(
            model_name='contatoquestionario',
            name='questionario_fk',
            field=models.ForeignKey
            (on_delete=django.db.models.deletion.CASCADE,
             to='questionario.Questionario'),
        ),
    ]
