# Generated by Django 2.1.7 on 2021-04-14 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0002_violenciascount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatoviolencia',
            name='categoria',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
