# Generated by Django 2.1.7 on 2021-04-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0002_violenciascount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatoviolencia',
            name='categoria',
            field=models.TextField(default='Ongs'),
        ),
    ]
