# Generated by Django 2.1.7 on 2021-03-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0002_salvardados'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroProfissionais',
            fields=[
                ('nome_profissional', models.CharField(max_length=30)),
                ('id_profissional', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='categoriaviolencia',
            name='vitimas_categoria',
            field=models.IntegerField(default=0),
        ),
    ]
