# Generated by Django 2.1.7 on 2021-03-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0002_salvardados'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadProfissionais',
            fields=[
                ('nome_profissional', models.CharField(max_length=30)),
                ('ds_profissional', models.TextField()),
                ('id_profissional', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
