# Generated by Django 2.1.7 on 2021-04-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0004_auto_20210416_1318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CadProfissionais',
        ),
    ]
