# Generated by Django 2.1.7 on 2021-05-17 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0005_delete_cadprofissionais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='categoria_violencia',
        ),
    ]
