
swagger: '2.0'
info:
  version: '0.0.1'
  title: Violeta API
  description: Documentação da API do Violeta
host: 0.0.0.0:8001
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /questionario:
    get:
      tags:
        - getQuestionario
      description: Retorna todas as árvores de decisão cadastradas.
      produces:
        - application/json
      responses:
        '200':
          description: questionario response
          schema:
            type: array
            items:
              $ref: '#/definitions/questionario'
        '404':
          description: questionário nao encontrado
    post:
      tags:
        - postQuestionario
      description: Cria uma nova árvore de decisão.
      produces:
        - application/json
      parameters:
        - name: questionario
          in: body
          description: Estrutura da árvore
          required: true
          schema:
            $ref: '#/definitions/novoQuestionario'
      responses:
        '200':
          description: questionario response
          schema:
            $ref: '#/definitions/questionario'
  /questionario/{id}:
    get:
      tags:
        - getQuestionario
      description: Retorna uma árvore de decisão específica.
      parameters:
        - name: id
          in: path
          description: ID da árvore
          required: true
          type: integer
          format: int64
      produces:
        - application/json
      responses:
        '200':
          description: questionario response
          schema:
            $ref: '#/definitions/questionario'
        '404':
          description: árvore não encontrada
    delete:
      tags:
        - deleteQuestionarioID
      description: Apaga a arvore especificada no id
      parameters:
        - name: id
          in: path
          description: ID da árvore
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: árvore apagada
        '404': 
          description: árvore nao encontrada
definitions:
  questionario:
    type: object
    required:
      - arvore_decisao
      - categoria_violencia
    properties:
      id:
        type: integer
        format: int64
      arvore_decisao:
        type: string
      categoria_violencia:
        type: integer
        format: int64
  novoQuestionario:
    type: object
    required:
      - arvore_decisao
      - categoria_violencia
    properties:
      arvore_decisao:
        type: string
      categoria_violencia:
        type: integer
        format: int64


# Instalar e Rodar server
# npm install -g http-server
# wget https://github.com/swagger-api/swagger-editor/releases/download/v2.10.4/swagger-editor.zip
# unzip swagger-editor.zip
# http-server swagger-editor
# Rodar Server
# http-server swagger-editor

# Necessário para visualizar sem configurar CORS
# https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf 